id: I08FFA5F9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T03:33:47+00:00'
last_modified: '2022-06-07T17:45:05.511069+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5842
  title: གྲུབ་མཐའ་ཆེན་མོའི་མཆན་འགྲེལ་དཀའ་གནད་མདུད་གྲོལ་བློ་གསལ་གཅེས་ནོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A67A:
      image_group_id: I1KG10684
      title: ''
      total_pages: 756
      order: 1
      base_file: A67A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
