id: I08FFA5F9
legacy_id: P003123
ocr_import_info:
  bdrc_scan_id: W5842
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T03:28:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:01:56.317337+00:00'
last_modified: 2022-09-04 11:02:35.517234
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W5842
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW5842
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་མཐའ་ཆེན་མོའི་མཆན་འགྲེལ་དཀའ་གནད་མདུད་གྲོལ་བློ་གསལ་གཅེས་ནོར།
  author: ཁལ་ཁ་ངག་དབང་དཔལ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.8894964841679489
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG10684:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10684
      total_pages: 756
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10684.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8894964841679489
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
