id: P003123
initial_creation_type: ocr
source_metadata:
  id: bdr:W5842
  title: གྲུབ་མཐའ་ཆེན་མོའི་མཆན་འགྲེལ་དཀའ་གནད་མདུད་གྲོལ་བློ་གསལ་གཅེས་ནོར།
  author: ''
  volumes:
    4af0d7f4afef429a8bcc03da1455db5f:
      image_group_id: I1KG10684
      title: ''
      volume_number: 1
      total_pages: 756
      base_file: v001.txt
